"""Admin integration control-center demo data.

The MVP does not call production systems. This dataset describes the adapter
contracts, health and exchange log the portal would expose when connected to
the Holding integration bus.
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone


NOW = datetime.now(timezone.utc)

SYSTEMS = [
    {
        "id": "egov-idp",
        "name": "eGov IDP",
        "owner": "Госорган",
        "purpose": "Единая авторизация предпринимателя",
        "adapter": "OIDC/SAML через интеграционную шину",
        "status": "ready",
        "sla": "99.5%",
        "lastEventAt": (NOW - timedelta(minutes=7)).isoformat(),
        "operations": 386,
        "latencyMs": 420,
        "nextStep": "Подключить продуктивный client_id после аккредитации стенда",
    },
    {
        "id": "gbd-ul",
        "name": "ГБД ЮЛ",
        "owner": "Госорган",
        "purpose": "Предзаполнение БИН, наименования, ОКЭД и адреса",
        "adapter": "REST adapter: /company/{bin}",
        "status": "mocked",
        "sla": "98.0%",
        "lastEventAt": (NOW - timedelta(minutes=19)).isoformat(),
        "operations": 142,
        "latencyMs": 730,
        "nextStep": "Заменить demo fixture на ESB endpoint, сохранить тот же контракт",
    },
    {
        "id": "nca-eds",
        "name": "НУЦ / ЭЦП",
        "owner": "Госорган",
        "purpose": "Подписание заявления и документов",
        "adapter": "NCALayer/NCANode compatible signing flow",
        "status": "mocked",
        "sla": "98.5%",
        "lastEventAt": (NOW - timedelta(hours=1, minutes=4)).isoformat(),
        "operations": 58,
        "latencyMs": 1280,
        "nextStep": "Подключить проверку CMS-подписи и timestamp",
    },
    {
        "id": "holding-esb",
        "name": "Единая интеграционная шина Холдинга",
        "owner": "Байтерек",
        "purpose": "Маршрутизация заявок в BPM дочерних организаций",
        "adapter": "Outbox + idempotency-key + status callback",
        "status": "ready",
        "sla": "99.0%",
        "lastEventAt": (NOW - timedelta(minutes=4)).isoformat(),
        "operations": 214,
        "latencyMs": 510,
        "nextStep": "Согласовать справочник кодов услуг и статусов BPM",
    },
    {
        "id": "bpm-damu",
        "name": "BPM Даму",
        "owner": "Даму",
        "purpose": "Передача заявки на субсидирование и получение статусов",
        "adapter": "ESB topic: applications.damu.subsidy",
        "status": "ready",
        "sla": "99.0%",
        "lastEventAt": (NOW - timedelta(minutes=13)).isoformat(),
        "operations": 96,
        "latencyMs": 640,
        "nextStep": "Добавить вложения PDF через document exchange adapter",
    },
    {
        "id": "bpm-akk",
        "name": "BPM АКК",
        "owner": "Аграрная кредитная корпорация",
        "purpose": "Передача заявок по агробизнесу и второй этап документов",
        "adapter": "ESB topic: applications.akk.agro",
        "status": "degraded",
        "sla": "97.0%",
        "lastEventAt": (NOW - timedelta(hours=2, minutes=22)).isoformat(),
        "operations": 41,
        "latencyMs": 2140,
        "nextStep": "Разобрать ошибки справочника регионов в callback",
    },
    {
        "id": "notifications",
        "name": "Email/SMS/WhatsApp gateway",
        "owner": "Байтерек",
        "purpose": "Уведомления о статусах и доработках",
        "adapter": "Template messages with delivery receipts",
        "status": "planned",
        "sla": "98.0%",
        "lastEventAt": None,
        "operations": 0,
        "latencyMs": None,
        "nextStep": "Подключить провайдера и таблицу delivery receipts",
    },
    {
        "id": "bi-analytics",
        "name": "BI / Аналитический центр",
        "owner": "Байтерек",
        "purpose": "Embedding дашбордов и выгрузка проектов для карты",
        "adapter": "Iframe embedding + scheduled dataset import",
        "status": "planned",
        "sla": "99.0%",
        "lastEventAt": None,
        "operations": 0,
        "latencyMs": None,
        "nextStep": "Согласовать embed URLs и наборы открытых показателей",
    },
]

EXCHANGES = [
    {
        "id": "int_000231",
        "createdAt": (NOW - timedelta(minutes=4)).isoformat(),
        "direction": "outbound",
        "systemId": "holding-esb",
        "operation": "application.submit",
        "status": "success",
        "application": "EPPB-2026-000124",
        "idempotencyKey": "app-EPPB-2026-000124-v1",
        "durationMs": 502,
        "payload": {"service": "damu-subsidy", "stage": "initial"},
    },
    {
        "id": "int_000230",
        "createdAt": (NOW - timedelta(minutes=7)).isoformat(),
        "direction": "inbound",
        "systemId": "egov-idp",
        "operation": "auth.callback",
        "status": "success",
        "application": None,
        "idempotencyKey": "auth-session-demo-admin",
        "durationMs": 418,
        "payload": {"role": "entrepreneur", "bin": "123456789012"},
    },
    {
        "id": "int_000229",
        "createdAt": (NOW - timedelta(minutes=19)).isoformat(),
        "direction": "outbound",
        "systemId": "gbd-ul",
        "operation": "company.prefill",
        "status": "success",
        "application": "draft",
        "idempotencyKey": "prefill-123456789012",
        "durationMs": 731,
        "payload": {"bin": "123456789012", "fields": ["name", "oked", "address"]},
    },
    {
        "id": "int_000228",
        "createdAt": (NOW - timedelta(hours=1, minutes=4)).isoformat(),
        "direction": "outbound",
        "systemId": "nca-eds",
        "operation": "document.sign",
        "status": "success",
        "application": "EPPB-2026-000124",
        "idempotencyKey": "sign-EPPB-2026-000124",
        "durationMs": 1282,
        "payload": {"document": "application.pdf", "signature": "cms-detached-demo"},
    },
    {
        "id": "int_000227",
        "createdAt": (NOW - timedelta(hours=2, minutes=22)).isoformat(),
        "direction": "inbound",
        "systemId": "bpm-akk",
        "operation": "status.callback",
        "status": "retrying",
        "application": "EPPB-2026-000119",
        "idempotencyKey": "callback-akk-000119-2",
        "durationMs": 2140,
        "payload": {"status": "needs_changes", "reason": "region code mismatch"},
    },
]

CONTRACTS = [
    {
        "operation": "company.prefill",
        "request": "BIN -> company profile",
        "response": "name, legal form, OKED, address, director, category",
        "source": "ГБД ЮЛ",
        "owner": "Integration team",
    },
    {
        "operation": "application.submit",
        "request": "Application snapshot + files + idempotency key",
        "response": "external BPM id + accepted timestamp",
        "source": "Единая интеграционная шина",
        "owner": "Service owner",
    },
    {
        "operation": "status.callback",
        "request": "BPM status + comment + required documents",
        "response": "ack + notification event id",
        "source": "BPM дочерней организации",
        "owner": "Back-office lead",
    },
]

